Add client functions for Operator Policy endpoints
rabbitmq/hop pull request #396
Opened 2023-09-12 16:43 UTC by awills96

Also updated test files to add operator policy Api tests.

2023-09-12 16:43 UTC, pivotal-cla commented
@awills96 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/hop&pullRequestId=396)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/hop&pullRequestId=396) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2023-09-12 17:21 UTC, michaelklishin requested changes

2023-09-12 17:21 UTC, michaelklishin commented on src/test/groovy/com/rabbitmq/http/client/ClientSpec.groovy
> +    d.put("ha-mode", "all")
Please replace this with something like queue length limit. [Classic mirrored queues are going away completely in the next 3-9 months](https://rabbitmq.com/ha.html).

2023-09-12 17:21 UTC, michaelklishin commented on src/test/groovy/com/rabbitmq/http/client/ClientSpec.groovy
> +    d.put("ha-mode", "all")
Same as above

2023-09-12 17:21 UTC, michaelklishin commented on src/test/groovy/com/rabbitmq/http/client/ClientSpec.groovy
> +    d.put("ha-mode", "all")
Same as above

2023-09-12 17:21 UTC, michaelklishin commented on src/test/groovy/com/rabbitmq/http/client/ReactorNettyClientSpec.groovy
> +        d.put("ha-mode", "all")
Same as above

2023-09-12 17:21 UTC, michaelklishin commented on src/test/groovy/com/rabbitmq/http/client/ReactorNettyClientSpec.groovy
> +        d.put("ha-mode", "all")
Same as above

2023-09-12 17:40 UTC, michaelklishin commented
The rest of the PR looks good to me. Thank you!

2023-09-13 01:59 UTC, merged

2023-09-13 01:59 UTC, michaelklishin commented
Thank you!

2023-09-13 09:45 UTC, acogoluegnes commented
@awills96 Thanks for for this contribution. Would you mind [signing the CLA](https://github.com/rabbitmq/hop/pull/396#issuecomment-1716085822)? Thanks!

2023-09-13 13:39 UTC, awills96 commented
Thanks, will do soon! I'm just waiting on some details and managerial approvals since I did do this on corporate behalf.

2023-09-15 14:09 UTC, pivotal-cla commented
@awills96 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/hop&pullRequestId=396)!